"""Initial schema with performance indexes

Revision ID: 5fa554c56c45
Revises: 
Create Date: 2026-02-02 18:01:04.969990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fa554c56c45'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_orders_matching', 'orders', ['market_id', 'side', 'price_bp', 'created_at'], unique=False)
    op.create_index('idx_trades_no_order', 'trades', ['no_order_id'], unique=False)
    op.create_index('idx_trades_yes_order', 'trades', ['yes_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_trades_yes_order', table_name='trades')
    op.drop_index('idx_trades_no_order', table_name='trades')
    op.drop_index('idx_orders_matching', table_name='orders')
    # ### end Alembic commands ###
